name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-version: [16.8.0, 19.1.0]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install React ${{ matrix.react-version }}
        run: |
          npm install react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }}
          npm install --no-save @types/react@${{ matrix.react-version }} @types/react-dom@${{ matrix.react-version }} || true

      - name: Run ESLint
        run: npm run lint

      - name: Run tests with coverage
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jav974/react-refsignal
          files: ./coverage/lcov.info
          fail_ci_if_error: true
